### PR TITLE
force dfds envelope and add schemaVersion

### PR DESCRIPTION
**Pull request by kralle333**
closes dfds/cloudplatform/issues/2467

# Additional Review Notes
None

### CODE REVIEW

**Review by andreasfrisch — DISMISSED** [review]
Two questions before I approve:

1) Are there existing documents that need updating regarding this forced change to message schemas?
2) Will this be a deterrent for people registering their current schemas, as we _do_ enforce an alteration of the existing message types.

**Comment by kralle333** [comment]
> Two questions before I approve:
> 
> 1. Are there existing documents that need updating regarding this forced change to message schemas?
> 2. Will this be a deterrent for people registering their current schemas, as we _do_ enforce an alteration of the existing message types.

No one is using the system. We only have one serious schema from Ross, which I will just coordinate with. He might have used the dfds envelope also. I am thinking of removing the rest

**Review by SEQUOIIA — APPROVED** [review]
👀

**Comment by kralle333** [comment]
> 👀

tak

**Pull request merged**
